/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosqlite.GUI;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.ListModel;
import proyectosqlite.dao.SQLConnection;
import proyectosqlite.dao.SQL_Etiquetas;
import proyectosqlite.dao.SQL_EtiquetasDeTarjetas;
import proyectosqlite.dao.SQL_Tarjetas;
import proyectosqlite.modelo.Etiqueta;
import proyectosqlite.modelo.Tarjeta;

/**
 *
 * @author Pablo Alonso Vazquez <pav.vigo@gmail.com>
 */
public class EditorTarjeta extends javax.swing.JFrame {

    private Tarjeta tarjeta = new Tarjeta(null, null, null, null);

    /**
     * Creates new form EditorTarjeta
     */
    public EditorTarjeta() {
        initComponents();
        this.setAlwaysOnTop(true);

        this.jla_Id.setText("id= ");
    }

    public EditorTarjeta(Tarjeta tar) {
        initComponents();
        this.setAlwaysOnTop(true);

        actualizarDatos(tar);

    }

    private Tarjeta adquirirDatos() {
      Tarjeta tarjeta= new Tarjeta();
        
        tarjeta.setIdTarjeta(this.tarjeta.getIdTarjeta());
        tarjeta.setNombre(jtf_Nombre.getText());
        tarjeta.setEjemplo(jta_Ejemplo.getText());
        tarjeta.setDescripcion(jta_Descripcion.getText());

        return tarjeta;
    }

    private void actualizarDatos(Tarjeta tar) {
        tarjeta = tar;
        this.jla_Id.setText("id= " + tarjeta.getIdTarjeta());
        this.jtf_Nombre.setText(tarjeta.getNombre());
        this.jta_Ejemplo.setText(tarjeta.getEjemplo());
        this.jta_Descripcion.setText(tarjeta.getDescripcion());
        jlist_Etiquetas.setModel(adquirirEtiquetas());

    }

    private ListModel<Etiqueta> adquirirEtiquetas() {

       
        ArrayList<Etiqueta> arrLEtiqueta = SQL_EtiquetasDeTarjetas.getEtiquetasdeTarjeta(tarjeta);
        Etiqueta[] arrayEtiq = new Etiqueta[arrLEtiqueta.size()];

        arrayEtiq = arrLEtiqueta.toArray(arrayEtiq);
        System.out.println(arrayEtiq.length);
        return new JList<Etiqueta>(arrayEtiq).getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Ejemplo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_Descripcion = new javax.swing.JTextArea();
        jtf_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jla_Id = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist_Etiquetas = new javax.swing.JList<>();
        bot_Borrar_Etiquetas = new javax.swing.JButton();
        jcb_ListaEtiquetas = new javax.swing.JComboBox<Etiqueta>();
        bot_añadirEtiqueta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jta_Ejemplo.setColumns(20);
        jta_Ejemplo.setRows(5);
        jScrollPane1.setViewportView(jta_Ejemplo);

        jta_Descripcion.setColumns(20);
        jta_Descripcion.setRows(5);
        jScrollPane2.setViewportView(jta_Descripcion);

        jLabel1.setText("Nombre");

        jLabel2.setText("Ejemplo");

        jLabel3.setText("Descripcion");

        jButton1.setText("Añadir nueva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jla_Id.setText("id=");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ArrayList<Etiqueta> arrLEtiqueta= new ArrayList<Etiqueta>();//SQL_Etiquetas.getEtiquetasdeTarjeta(tarjeta);
        Etiqueta[] arrayEtiq = new Etiqueta[arrLEtiqueta.size()];
        arrayEtiq = arrLEtiqueta.toArray(arrayEtiq);
        jlist_Etiquetas.setModel(new JList<Etiqueta>(arrayEtiq).getModel()
        );
        jScrollPane3.setViewportView(jlist_Etiquetas);

        bot_Borrar_Etiquetas.setText("Borrar Etiqueta");
        bot_Borrar_Etiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_Borrar_EtiquetasActionPerformed(evt);
            }
        });

        ArrayList<Etiqueta> etiquetas = SQL_Etiquetas.getEtiquetas();
        Etiqueta[] eti =etiquetas.toArray(new Etiqueta[etiquetas.size()]);
        jcb_ListaEtiquetas.setModel(new javax.swing.DefaultComboBoxModel<Etiqueta>(eti));

        bot_añadirEtiqueta.setText("Añadir Etiqueta");
        bot_añadirEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_añadirEtiquetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jla_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcb_ListaEtiquetas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bot_Borrar_Etiquetas)
                                    .addComponent(bot_añadirEtiqueta))
                                .addContainerGap(205, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jla_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_ListaEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bot_añadirEtiqueta)))
                    .addComponent(bot_Borrar_Etiquetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //nueva tarjeta.
        tarjeta = adquirirDatos();
        tarjeta.setIdTarjeta(null);
        SQL_Tarjetas.añadirTarjeta(tarjeta);
        actualizarDatos(SQL_Tarjetas.getUltimaTarjeta());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // actualizar tarjeta
        tarjeta = adquirirDatos();
        SQL_Tarjetas.updateTarjeta(tarjeta);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        proyectosqlite.ProyectoSQLite.filTar.setEnabled(true);
        proyectosqlite.ProyectoSQLite.filTar.setFocusable(true);
    }//GEN-LAST:event_formWindowClosing

    private void bot_añadirEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_añadirEtiquetaActionPerformed
        SQL_EtiquetasDeTarjetas.añadirEtiquetaATarjeta(tarjeta, (Etiqueta) jcb_ListaEtiquetas.getSelectedItem());
        jlist_Etiquetas.setModel(adquirirEtiquetas());
        jScrollPane3.setViewportView(jlist_Etiquetas);


    }//GEN-LAST:event_bot_añadirEtiquetaActionPerformed

    private void bot_Borrar_EtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_Borrar_EtiquetasActionPerformed
        System.out.println("eti=" + jlist_Etiquetas.getSelectedIndex());
        SQL_EtiquetasDeTarjetas.deleteEtiquetaDeTarjeta((Etiqueta) jlist_Etiquetas.getSelectedValue(), tarjeta);
        jlist_Etiquetas.setModel(adquirirEtiquetas());
        jScrollPane3.setViewportView(jlist_Etiquetas);

    }//GEN-LAST:event_bot_Borrar_EtiquetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_Borrar_Etiquetas;
    private javax.swing.JButton bot_añadirEtiqueta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<Etiqueta> jcb_ListaEtiquetas;
    private javax.swing.JLabel jla_Id;
    private javax.swing.JList<Etiqueta> jlist_Etiquetas;
    private javax.swing.JTextArea jta_Descripcion;
    private javax.swing.JTextArea jta_Ejemplo;
    private javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
