/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosqlite.GUI;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.table.TableModel;
import proyectosqlite.dao.SQLConnection;
import proyectosqlite.GUI.Componentes.TaMoTarjetas;
import proyectosqlite.modelo.Etiqueta;
import proyectosqlite.modelo.Tarjeta;

/**
 *
 * @author Pablo Alonso Vazquez <pav.vigo@gmail.com>
 */
public class FiltradorTarjetas extends javax.swing.JFrame {

    /**
     * Creates new form FiltradorTarjetas
     */
    private void actualizarTabla(ArrayList<Tarjeta> arrTar){
        arrList_tarjetas = arrTar;
         TaMoTarjetas tamo = new TaMoTarjetas(arrList_tarjetas);
        jTaTarjetas.setModel(tamo);
        tamo.fireTableDataChanged();
        jTaTarjetas.updateUI();
        
        
        
    }
    public FiltradorTarjetas() {
        initComponents();
        actualizarTabla(SQLConnection.getInstance().getTarjetas(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTaTarjetas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_Etiquetas = new javax.swing.JList<>();
        bot_Filtrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist_Etiquetas1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        bot_actualizar = new javax.swing.JButton();
        bot_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTaTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTaTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTaTarjetasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTaTarjetas);

        ArrayList<Etiqueta> arrLEtiqueta= SQLConnection.getInstance().getEtiquetas();
        Etiqueta[] arrayEtiq = new Etiqueta[arrLEtiqueta.size()];
        arrayEtiq = arrLEtiqueta.toArray(arrayEtiq);
        jlist_Etiquetas.setModel(new JList<Etiqueta>(arrayEtiq).getModel()
        );
        jScrollPane2.setViewportView(jlist_Etiquetas);

        bot_Filtrar.setText("Filtrar");
        bot_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_FiltrarActionPerformed(evt);
            }
        });

        ArrayList<Etiqueta> arrLEtiquetaCompleta= SQLConnection.getInstance().getEtiquetas();
        Etiqueta[] arrayEtiqCompleta = new Etiqueta[arrLEtiquetaCompleta.size()];
        arrayEtiqCompleta = arrLEtiquetaCompleta.toArray(arrayEtiqCompleta);
        jlist_Etiquetas1.setModel(new JList<Etiqueta>(arrayEtiqCompleta).getModel()
        );
        jScrollPane3.setViewportView(jlist_Etiquetas1);

        jButton1.setText("Nueva Tarjeta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bot_actualizar.setText("actualizar Tarjeta");
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });

        bot_borrar.setText("Borrar Tarjeta");
        bot_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bot_Filtrar)
                        .addGap(233, 233, 233)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bot_actualizar)
                            .addComponent(bot_borrar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_Filtrar)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(bot_actualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bot_borrar)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTaTarjetasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaTarjetasMouseReleased
       int x =jTaTarjetas.getSelectedRow();
        System.out.println("-.,-"+x);
       
        
        
        
ArrayList<Etiqueta> arrLEtiqueta= SQLConnection.getInstance().getEtiquetasdeTarjeta(arrList_tarjetas.get(x));

Etiqueta[] arrayEtiq = new Etiqueta[arrLEtiqueta.size()];
arrayEtiq = arrLEtiqueta.toArray(arrayEtiq);
jlist_Etiquetas.setModel(new JList<Etiqueta>(arrayEtiq).getModel()
    );
        
    }//GEN-LAST:event_jTaTarjetasMouseReleased

    private void bot_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_FiltrarActionPerformed
        arrList_tarjetas = SQLConnection.getInstance().getTarjetasFiltradas("",jlist_Etiquetas1.getSelectedValuesList());
        actualizarTabla(arrList_tarjetas);
        
        
    }//GEN-LAST:event_bot_FiltrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      editTar = new EditorTarjeta();
              editTar.setVisible(true);
              this.setEnabled(false);
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        int x =jTaTarjetas.getSelectedRow();
        System.out.println("-.,-"+x);
       
        
        
       
if(x != -1){
editTar = new EditorTarjeta(arrList_tarjetas.get(x));
editTar.setVisible(true);
this.setEnabled(false);
this.setFocusable(false);
}


    
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_borrarActionPerformed
        int x =jTaTarjetas.getSelectedRow();
        SQLConnection.getInstance().deleteTarjeta(arrList_tarjetas.get(x));
        
        actualizarTabla();
    }//GEN-LAST:event_bot_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltradorTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltradorTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltradorTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltradorTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiltradorTarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_Filtrar;
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_borrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTaTarjetas;
    private javax.swing.JList<Etiqueta> jlist_Etiquetas;
    private javax.swing.JList<Etiqueta> jlist_Etiquetas1;
    // End of variables declaration//GEN-END:variables
 private ArrayList<Tarjeta> arrList_tarjetas;
 private EditorTarjeta editTar;

    private void actualizarTabla() {
        arrList_tarjetas = SQLConnection.getInstance().getTarjetas("");
        actualizarTabla(arrList_tarjetas);
    }
}
